try:  
    print(10+10)
finally:
    print("error occured")